### ISSUE TITLE
License for quassel.py file?

### ISSUE THREAD

**Issue by jleclanche** [Zren/QuasselPy#1]
Hi

I'm reusing your quassel.py file for a similar personal project. What license is it under?

**Comment by Zren** [comment]
Hmmm. [MIT](http://choosealicense.com/) is simple enough while letting you hack n slash it.

https://github.com/Zren/QuasselPy/blob/master/quassel.py#L7

Also added a MessageType class which is sorta like an enum that I had locally.

**Comment by jleclanche** [comment]
Thanks! Good work, btw. :)

**Comment by jleclanche** [comment]
This is the result, if you're curious: https://leclan.ch/irc/

WIP of course; I'll put it on Github once it's a bit more complete :)
